logging:
  config: classpath:log4j2.xml
server:
  application-name: camel-artemis-service
  work-time: 100
  activemq:
    queues:
      input-endpoint: "jms:queue:inputqueue"
      output-order-endpoint: "jms:queue:orderoutputqueue"
spring:
  artemis:
    mode: native
    host: localhost
    port: 61616
    user: user
    password: user

