logging:
  config: classpath:log4j2.xml
server:
  application-name: camel-artemis-service
  work-time: 100
  activemq:
    queues:
      input-output-endpoint:      "jmsComponent:queue:inputToOutputQueue"
      output-endpoint:            "jmsComponent:queue:outputQueue"
      input-output-bean-endpoint: "jmsComponent:queue:inputToOutputBeanQueue"
      output-bean-endpoint:       "jmsComponent:queue:outputToBeanQueue"
camel:
  activemq:
    brokerUrl: tcp://localhost:61616
    user: user
    password: user
    concurrentConsumers: 500
    redeliveryCount: 5
    redeliveryDelayMs: 1000


